### ISSUE TITLE
UUID not saved to database on user creation - workaround needed

### ISSUE THREAD

**Issue by TheOuen** [Dulajdeshan/strapi-advanced-uuid#56]
When creating a new user, the UUID is generated automatically but is not being saved to the database. The UUID only appears in the database after manually re-saving the entry in the Strapi admin panel.
Has anyone encountered this issue before? If so, what workaround did you use to ensure the UUID is saved immediately upon user creation?
Any help or suggestions would be greatly appreciated.

**Comment by MaxDiMart** [comment]
I have the same problem. @TheOuen , did you manage to find a solution?

**Comment by Dulajdeshan** [comment]
> I have the same problem. @TheOuen , did you manage to find a solution?

Hi @MaxDiMart Would you be able to add more details here. 

1. `strapi-advanced-uuid` version
2. Are you having this issue in the GUI, or API?
3. If possible would you be able to share the schema of the User?

**Comment by MaxDiMart** [comment]
> > I have the same problem. @TheOuen , did you manage to find a solution?
> 
> Hi @MaxDiMart Would you be able to add more details here.
> 
> 1. `strapi-advanced-uuid` version
> 2. Are you having this issue in the GUI, or API?
> 3. If possible would you be able to share the schema of the User?

Hi. When creating a record, the field is generated and displayed. In API responses, it is always null. But in the GUI, update the record, and then the field comes to the API response correctly.

1. "strapi-advanced-uuid": "^1.3.0",
2. I have this problem in API. In GUI uuid is displayed correctly.
3. Field: refCode `{
  "kind": "collectionType",
  "collectionName": "up_users",
  "info": {
    "name": "user",
    "description": "",
    "singularName": "user",
    "pluralName": "users",
    "displayName": "User"
  },
  "options": {
    "draftAndPublish": false
  },
  "attributes": {
    "username": {
      "type": "string",
      "minLength": 3,
      "unique": true,
      "configurable": false,
      "required": true
    },
    "email": {
      "type": "email",
      "minLength": 6,
      "configurable": false,
      "required": true
    },
    "provider": {
      "type": "string",
      "configurable": false
    },
    "password": {
      "type": "password",
      "minLength": 6,
      "configurable": false,
      "private": true,
      "searchable": false
    },
    "resetPasswordToken": {
      "type": "string",
      "configurable": false,
      "private": true,
      "searchable": false
    },
    "confirmationToken": {
      "type": "string",
      "configurable": false,
      "private": true,
      "searchable": false
    },
    "confirmed": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "blocked": {
      "type": "boolean",
      "default": false,
      "configurable": false
    },
    "role": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "plugin::users-permissions.role",
      "inversedBy": "users",
      "configurable": false
    },
    "firstName": {
      "type": "string"
    },
    "lastName": {
      "type": "string"
    },
    "photoUrl": {
      "type": "string"
    },
    "tgId": {
      "type": "biginteger",
      "unique": true
    },
    "timeZoneOffset": {
      "type": "integer",
      "default": 0,
      "private": true
    },
    "user_devices": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::user-device.user-device",
      "mappedBy": "users_permissions_user"
    },
    "projects": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::history-user-with-project.history-user-with-project",
      "mappedBy": "users"
    },
    "balance": {
      "type": "integer",
      "default": 0
    },
    "refCode": {
      "type": "customField",
      "options": {
        "uuid-format": "^[A-Za-z0-9]{6}$"
      },
      "customField": "plugin::strapi-advanced-uuid.uuid"
    },
    "exp": {
      "type": "integer",
      "default": 0,
      "required": false
    },
    "level": {
      "type": "relation",
      "relation": "manyToOne",
      "target": "api::level.level",
      "inversedBy": "users"
    },
    "referral_histories": {
      "type": "relation",
      "relation": "oneToMany",
      "target": "api::referral-history.referral-history",
      "mappedBy": "parent"
    },
    "referral_history": {
      "type": "relation",
      "relation": "oneToOne",
      "target": "api::referral-history.referral-history",
      "mappedBy": "child"
    }
  }
}
`

**Comment by Dulajdeshan** [comment]
Hi @TheOuen @MaxDiMart This has been fixed in [v1.4.1](https://github.com/Dulajdeshan/strapi-advanced-uuid/releases/tag/v1.4.1)

Happy Coding 😃 !!

**Comment by MaxDiMart** [comment]
@Dulajdeshan , unfortunately the problem still exists. And the field is not returned to API

**Comment by Dulajdeshan** [comment]
> @Dulajdeshan , unfortunately the problem still exists. And the field is not returned to API

Hi @MaxDiMart Did you try clearing your strapi cache. Its working for me.

![image](https://github.com/user-attachments/assets/e1917ae9-c6f2-4618-9b72-cade8d284879)

**Comment by MaxDiMart** [comment]
> > @Dulajdeshan , unfortunately the problem still exists. And the field is not returned to API
> 
> Hi @MaxDiMart Did you try clearing your strapi cache? Its working for me.
> 
> ![image](https://private-user-images.githubusercontent.com/38158937/373958994-e1917ae9-c6f2-4618-9b72-cade8d284879.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjk3MjgsIm5iZiI6MTcyODIyOTQyOCwicGF0aCI6Ii8zODE1ODkzNy8zNzM5NTg5OTQtZTE5MTdhZTktYzZmMi00NjE4LTliNzItY2FkZThkMjg0ODc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDE1NDM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YjAwNGNiMzhhN2YyMzRkMzNjNDAzMTJhZGVmNWNhNDkzZGYwMmExODVhMGJhNWFhMDViYmFmZDQyMzdhNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MjF1hJ34f0USPOdNtSco_WiF7Xla1Ne939wo0a446Xs)

@Dulajdeshan , thank you very much. Now the field is returned in the API response.
But I found a new problem. When I update my record (update the user balance) my refCode field is updated. But I did not add this field for updating.

`{
  method: 'update',
  options: {},
  timeout: false,
  cancelOnTimeout: false,
  bindings: [ 333, 'zP0UBh', 2024-10-06T22:07:57.529Z, 10 ],
  __knexQueryUid: 'mc8DANIdivv0YljTI7xaP',
  sql: 'update `up_users` set `balance` = ?, `ref_code` = ?, `updated_at` = ? where (`id` = ?)',
  returning: undefined
}
`

`        
const res = await strapi.entityService.update('plugin::users-permissions.user', 10, {
          data: {
            balance: 333,
          },
          trx
        });`

**Comment by krissy** [comment]
Hi @MaxDiMart @Dulajdeshan - I'm hitting the same problem with my UUID changing on updating my user record. Is there a workaround for this? (can raise a new issue if unrelated to this bug fix)
